import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-12 max-w-7xl mx-auto">
          <nav className="flex gap-10">
            <Link href="/">Home</Link>
            <Link href="/suspense">With Suspense</Link>
            <Link href="/parallel">With Parallel</Link>
            <Link href="/parallel/test">Test route</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
